baseURL = "https://tszminglee.github.io"
#baseURL = "http://www.example.com"
languageCode = "en-us"
title = "Tommy Tsz-Ming Lee"
theme = "hugo-coder-master"

paginate = 20

pygmentsStyle = "b2"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Tommy Tsz-Ming Lee 李梓明"
    description = "Tommy Tsz-Ming Lee's personal website"
    #keywords =
    info = "I identify myself as a linguist. I am grateful to wherever language takes me to."
    avatarurl = "images/profile_picture2.jpg"
    footercontent = "Email: tszmingl(at)usc(dot)edu"

    dateformat = "January 2, 2006"

    hideFooter = false
    hideCredits = false
    hideCopyright = false
    since = 2018

    # Git Commit in Footer, uncomment the line below to enable it.
    #commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Use inverted colors
    #inverted = true

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorScheme = "auto"

    # Hide the toggle button, along with the associated vertical divider
    hideColorSchemeToggle = false


    # Custom CSS
    custom_css = []

################################
[[params.social]]
    name = "ResearchGate"
    icon = "fab fa-researchgate"
    weight = 5
    url = "https://www.researchgate.net/profile/Tommy_Tsz_Ming_Lee"

################################
    [[menu.main]]
        name = "About"
        weight = 1
        url  = "about/"

    [[menu.main]]
        name = "Projects"
        weight = 3
        url = "projects/"

    [[menu.main]]
        name = "Talks"
        weight = 8
        url = "talks/"

    [[menu.main]]
            name = "Papers"
            weight = 5
            url = "papers/"

    [[menu.main]]
        name = "Podcast"
        weight = 10
        url = "podcast/"
#    [[menu.main]]
#        name = "Misc"
#        weight = 15
#        url = "/misc/"

#how to update the website

#1 Update the contents in the folder "webpage"

#2 Publish the website by:

#hugo -d ../tszminglee.github.io

#3 Check the status of the folder
#cd ../tszminglee.github.io
#git status

#4 add content and commit
#git add --all
#git commit -m "0824 commit"
#git push origin master
