baseURL = "https://tszminglee.github.io"
#baseURL = "http://www.example.com"
languageCode = "en-us"
title = "Tommy Tsz-Ming Lee"
theme = "hugo-coder"


[params]
    author = "Tommy Tsz-Ming Lee 李梓明"
    description = "Tommy Tsz-Ming Lee's personal website"
    #keywords =
    info = "I am forth-year Ph.D. student in the Department of Linguistics at University of Southern California. My research focuses on the structure of natural languages and its mapping onto meanings."
    avatarurl = "images/profile_picture2.jpg"
    footercontent = "Email: tszmingl(at)usc(dot)edu"

    dateformat = "January 2, 2006"

    hideCredits = false
    hideCopyright = false

    # Git Commit in Footer, uncomment the line below to enable it.
    #commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Use inverted colors
    inverted = true

    # Custom CSS
    custom_css = []

################################
[[params.social]]
    name = "ResearchGate"
    icon = "fab fa-researchgate"
    weight = 5
    url = "https://www.researchgate.net/profile/Tommy_Tsz_Ming_Lee"

################################
#    [[menu.main]]
#        name = "Home"
#        weight = 1
#        url  = "/posts/"
    [[menu.main]]
        name = "Recent"
        weight = 3
        url = "recent/"

    [[menu.main]]
        name = "Presentations"
        weight = 8
        url = "presentations/"

    [[menu.main]]
            name = "Papers"
            weight = 5
            url = "papers/"

    [[menu.main]]
        name = "CV"
        weight = 10
        url = "cv/"
#    [[menu.main]]
#        name = "Misc"
#        weight = 15
#        url = "/misc/"

#how to update the website

#1 Update the contents in the folder "webpage"

#2 Publish the website by:

#hugo -d ../tszminglee.github.io

#3 Check the status of the folder
#cd ../tszminglee.github.io
#git status

#4 add content and commit
#git add --all
#git commit -m "0824 commit"
#git push origin master
