baseURL = "http://tszminglee.github.io"
#baseURL = "http://www.example.com"
languageCode = "en-us"
title = "Tommy Tsz-Ming Lee"
theme = "hugo-coder"


[params]
    author = "Tommy Tsz-Ming Lee 李梓明"
    description = "Tommy's personal website"
    #keywords =
    info = "I am second-year Ph.D. student in Linguistics at University of Southern California. I am interested in syntax and semantics, as well as East Asian languages."
    avatarurl = "images/profile_picture.jpg"
    footercontent = "Email: tszmingl(at)usc(dot)edu"

    dateformat = "January 2, 2006"

    hideCredits = false
    hideCopyright = false

    # Git Commit in Footer, uncomment the line below to enable it.
    #commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Use inverted colors
    inverted = true

    # Custom CSS
    custom_css = []

################################
[[params.social]]
    name = "ResearchGate"
    icon = "fab fa-researchgate"
    weight = 5
    url = "https://www.researchgate.net/profile/Tommy_Tsz_Ming_Lee"

################################
#    [[menu.main]]
#        name = "Home"
#        weight = 1
#        url  = "/posts/"
    [[menu.main]]
        name = "Research"
        weight = 5
        url = "research/"
    [[menu.main]]
        name = "CV"
        weight = 10
        url = "cv/"
#    [[menu.main]]
#        name = "Misc"
#        weight = 15
#        url = "/misc/"
